#!/usr/bin/env bash
# generate-env-config.sh — read .env and write env-config.js for runtime
set -e
ENV_FILE=.env
OUT_FILE=env-config.js
if [ ! -f "$ENV_FILE" ]; then
echo "# .env not found — create one from .env.example or set API_BASE_URL env var" >&2
exit 1
fi
# Read API_BASE_URL from .env
API_BASE_URL=$(grep -E '^API_BASE_URL=' "$ENV_FILE" | sed -E 's/^API_BASE_URL=(.*)$/\1/' | tr -d '\r')
API_BASE_URL=${API_BASE_URL:-""}
# Ensure the generated JS contains a quoted string or null
if [ -n "$API_BASE_URL" ]; then
	API_JS_VALUE="\"$API_BASE_URL\""
else
	API_JS_VALUE="null"
fi

cat > "$OUT_FILE" <<EOF
// Generated by generate-env-config.sh — safe to serve publicly
window.__ENV = window.__ENV || {};
window.__ENV.API_BASE_URL = $API_JS_VALUE;
EOF

echo "Wrote $OUT_FILE (API_BASE_URL=${API_BASE_URL})"
